CREATE TABLE IF NOT EXISTS users (
  uid TEXT PRIMARY KEY,
  username TEXT NOT NULL,
  displayName TEXT NOT NULL,
  handle TEXT NOT NULL UNIQUE,
  photoURL TEXT,
  onboardingCompleted INTEGER NOT NULL DEFAULT 0,
  deletionRequestedAt INTEGER,
  deletionScheduledAt INTEGER,
  firebaseRefreshToken TEXT,
  updatedAt INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS posts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uid TEXT NOT NULL,
  postImage TEXT NOT NULL,
  caption TEXT,
  likesCount INTEGER DEFAULT 0,
  createdAt INTEGER NOT NULL,
  FOREIGN KEY (uid) REFERENCES users(uid) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS songs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uid TEXT NOT NULL,
  post_id INTEGER,
  trackName TEXT NOT NULL,
  artistName TEXT NOT NULL,
  albumCover TEXT,
  spotifyUrl TEXT,
  createdAt INTEGER NOT NULL,
  FOREIGN KEY (uid) REFERENCES users(uid) ON DELETE CASCADE,
  FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS messages (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  chatId TEXT NOT NULL,
  senderUid TEXT NOT NULL,
  text TEXT NOT NULL,
  createdAt INTEGER NOT NULL,
  FOREIGN KEY (senderUid) REFERENCES users(uid) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_rate_limits (
  uid TEXT NOT NULL,
  action TEXT NOT NULL,
  windowStart INTEGER NOT NULL,
  requestCount INTEGER NOT NULL DEFAULT 0,
  penaltyLevel INTEGER NOT NULL DEFAULT 0,
  blockedUntil INTEGER NOT NULL DEFAULT 0,
  updatedAt INTEGER NOT NULL,
  PRIMARY KEY (uid, action)
);
