CREATE TABLE IF NOT EXISTS users (
  uid TEXT PRIMARY KEY,
  username TEXT NOT NULL,
  handle TEXT NOT NULL UNIQUE,
  photoURL TEXT,
  updatedAt INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS posts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uid TEXT NOT NULL,
  postImage TEXT NOT NULL,
  caption TEXT,
  likesCount INTEGER DEFAULT 0,
  createdAt INTEGER NOT NULL,
  FOREIGN KEY (uid) REFERENCES users(uid) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS songs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uid TEXT NOT NULL,
  post_id INTEGER,
  trackName TEXT NOT NULL,
  artistName TEXT NOT NULL,
  albumCover TEXT,
  spotifyUrl TEXT,
  createdAt INTEGER NOT NULL,
  FOREIGN KEY (uid) REFERENCES users(uid) ON DELETE CASCADE,
  FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS messages (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  chatId TEXT NOT NULL,
  senderUid TEXT NOT NULL,
  text TEXT NOT NULL,
  createdAt INTEGER NOT NULL,
  FOREIGN KEY (senderUid) REFERENCES users(uid) ON DELETE CASCADE
);
