#:schema https://cloudflare.com
name = "solify"
compatibility_date = "2026-04-14"

[build]
compatibility_flags = [ "typescript_pages_functions" ]

# 1. Your Profile Pictures Bucket Connection
[[r2_buckets]]
binding = "SOLIFY_PROFILE_PICTURES_BUCKET"
bucket_name = "solify-profile-pics"

# 2. Your User Profiles Database Connection
[[d1_databases]]
binding = "DB"
database_name = "solify-user-db"
database_id = "7b007987-7ffc-4e78-9d97-601984075a19"